[pytest]
testpaths = tests
addopts = -v --tb=short
markers =
    usuarios: Testes do endpoint de Usuários
    login: Testes do endpoint de Login
    produtos: Testes do endpoint de Produtos
    carrinho: Testes do endpoint de Carrinho
